// <auto-generated />
using System;
using Ecommerce.Infrastructure.Platform;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Platform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261008224652_Identity")]
    partial class Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_tenant_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("TenantId", "UserId")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_email");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasAlternateKey("Code")
                        .HasName("ak_plans_code");

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199c4a0-0000-7000-8000-000000000001"),
                            Code = "essencial",
                            Name = "Essencial"
                        },
                        new
                        {
                            Id = new Guid("0199c4a0-0000-7000-8000-000000000002"),
                            Code = "profissional",
                            Name = "Profissional"
                        },
                        new
                        {
                            Id = new Guid("0199c4a0-0000-7000-8000-000000000003"),
                            Code = "completo",
                            Name = "Completo"
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.PlanLimit", b =>
                {
                    b.Property<string>("PlanCode")
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Key")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("PlanCode", "Key")
                        .HasName("pk_plan_limits");

                    b.ToTable("plan_limits", (string)null);

                    b.HasData(
                        new
                        {
                            PlanCode = "essencial",
                            Key = "users",
                            Value = 2
                        },
                        new
                        {
                            PlanCode = "profissional",
                            Key = "users",
                            Value = 5
                        },
                        new
                        {
                            PlanCode = "completo",
                            Key = "users",
                            Value = 10
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("database_key");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("essencial")
                        .HasColumnName("plan_code");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("trade_name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_cnpj");

                    b.HasIndex("PlanCode")
                        .HasDatabaseName("ix_tenants_plan_code");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_domains");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domains_host");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_domains_tenant_id");

                    b.ToTable("tenant_domains", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Ecommerce.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_accounts_user_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Identity.TenantMembership", b =>
                {
                    b.HasOne("Ecommerce.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("Ecommerce.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_user_accounts_user_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.PlanLimit", b =>
                {
                    b.HasOne("Ecommerce.Domain.Platform.Plan", null)
                        .WithMany("Limits")
                        .HasForeignKey("PlanCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_limits_plans_plan_code");
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.Tenant", b =>
                {
                    b.HasOne("Ecommerce.Domain.Platform.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_plans_plan_code");
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.TenantDomain", b =>
                {
                    b.HasOne("Ecommerce.Domain.Platform.Tenant", null)
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_domains_tenants_tenant_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.Plan", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Ecommerce.Domain.Platform.Tenant", b =>
                {
                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
