// <auto-generated />
using System;
using Ecommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20261009170001_VehicleCompatibility")]
    partial class VehicleCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("internal_code");

                    b.Property<int?>("LengthCm")
                        .HasColumnType("integer")
                        .HasColumnName("length_cm");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WeightG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_g");

                    b.Property<int?>("WidthCm")
                        .HasColumnType("integer")
                        .HasColumnName("width_cm");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("TenantId", "InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_parts_tenant_id_internal_code");

                    b.HasIndex("TenantId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_parts_tenant_id_status_updated_at");

                    b.ToTable("parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_parts_dimensions_positive", "coalesce(length_cm, 1) > 0 AND coalesce(width_cm, 1) > 0 AND coalesce(height_cm, 1) > 0 AND coalesce(weight_g, 1) > 0");

                            t.HasCheckConstraint("ck_parts_price_positive", "price > 0");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VehicleVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_version_id");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("integer")
                        .HasColumnName("year_from");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer")
                        .HasColumnName("year_to");

                    b.HasKey("Id")
                        .HasName("pk_part_compatibilities");

                    b.HasIndex("VehicleVersionId")
                        .HasDatabaseName("ix_part_compatibilities_vehicle_version_id");

                    b.HasIndex("TenantId", "VehicleVersionId")
                        .HasDatabaseName("ix_part_compatibilities_tenant_id_vehicle_version_id");

                    b.HasIndex("PartId", "VehicleVersionId", "YearFrom", "YearTo")
                        .IsUnique()
                        .HasDatabaseName("ix_part_compatibilities_part_id_vehicle_version_id_year_from_y");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PartId", "VehicleVersionId", "YearFrom", "YearTo"), false);

                    b.ToTable("part_compatibilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_part_compatibilities_years", "(year_from IS NULL AND year_to IS NULL) OR (year_from IS NOT NULL AND year_to IS NOT NULL AND year_from <= year_to)");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartOemCode", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PartId", "Code")
                        .HasName("pk_part_oem_codes");

                    b.HasIndex("TenantId", "Code")
                        .HasDatabaseName("ix_part_oem_codes_tenant_id_code");

                    b.ToTable("part_oem_codes", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_content_type");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_part_photos");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_part_photos_part_id");

                    b.HasIndex("TenantId", "PartId", "Position")
                        .HasDatabaseName("ix_part_photos_tenant_id_part_id_position");

                    b.ToTable("part_photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_part_photos_position", "position >= 0 AND position < 20");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.Stock", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PartId")
                        .HasName("pk_stocks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stocks_tenant_id");

                    b.ToTable("stocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_stocks_on_hand_non_negative", "on_hand >= 0");

                            t.HasCheckConstraint("ck_stocks_reserved_non_negative", "reserved >= 0");

                            t.HasCheckConstraint("ck_stocks_reserved_within_on_hand", "reserved <= on_hand");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_stock_movements_part_id");

                    b.HasIndex("TenantId", "PartId", "At")
                        .HasDatabaseName("ix_stock_movements_tenant_id_part_id_at");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_reservations");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_stock_reservations_part_id");

                    b.HasIndex("TenantId", "Reference")
                        .HasDatabaseName("ix_stock_reservations_tenant_id_reference");

                    b.ToTable("stock_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservations_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.StoreSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ReservationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_minutes");

                    b.HasKey("TenantId")
                        .HasName("pk_store_settings");

                    b.ToTable("store_settings", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Store.StoreBranding", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("about");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("background_color");

                    b.Property<string>("Footer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("footer");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("logo_content_type");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_id");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("return_policy");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("text_color");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_store_brandings");

                    b.ToTable("store_brandings", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Vault.TenantDataKey", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MasterKeyVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("master_key_version");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_data_keys");

                    b.ToTable("tenant_data_keys", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Vault.TenantSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hint");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_version");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_secrets");

                    b.HasIndex("TenantId", "Kind", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_secrets_tenant_id_kind_name");

                    b.ToTable("tenant_secrets", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Vehicles.VehicleBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_brands");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_brands_name");

                    b.ToTable("vehicle_brands", "ref");
                });

            modelBuilder.Entity("Ecommerce.Domain.Vehicles.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_models");

                    b.HasIndex("BrandId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_models_brand_id_name");

                    b.ToTable("vehicle_models", "ref");
                });

            modelBuilder.Entity("Ecommerce.Domain.Vehicles.VehicleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("boolean")
                        .HasColumnName("discontinued");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("engine");

                    b.Property<string>("MlReference")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ml_reference");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer")
                        .HasColumnName("year_from");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer")
                        .HasColumnName("year_to");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_versions");

                    b.HasIndex("ModelId", "Engine", "YearFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_versions_model_id_engine_year_from");

                    b.ToTable("vehicle_versions", "ref", t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_versions_years", "year_to IS NULL OR year_to >= year_from");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartCompatibility", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithMany("Compatibilities")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_compatibilities_parts_part_id");

                    b.HasOne("Ecommerce.Domain.Vehicles.VehicleVersion", null)
                        .WithMany()
                        .HasForeignKey("VehicleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_compatibilities_vehicle_versions_vehicle_version_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartOemCode", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithMany("OemCodes")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_oem_codes_parts_part_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.PartPhoto", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithMany("Photos")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_photos_parts_part_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.Stock", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithOne()
                        .HasForeignKey("Ecommerce.Domain.Inventory.Stock", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stocks_parts_part_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.StockMovement", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_parts_part_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.StockReservation", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservations_parts_part_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("Ecommerce.Domain.Vehicles.VehicleBrand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_models_vehicle_brands_brand_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Vehicles.VehicleVersion", b =>
                {
                    b.HasOne("Ecommerce.Domain.Vehicles.VehicleModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_versions_vehicle_models_model_id");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Part", b =>
                {
                    b.Navigation("Compatibilities");

                    b.Navigation("OemCodes");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
